name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-lint-typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install -r requirements.txt
      - name: Lint
        run: . .venv/bin/activate && ruff check .
      - name: Typecheck
        run: . .venv/bin/activate && mypy apps
      - name: Tests
        run: . .venv/bin/activate && pytest -q
