name: Docker Build & Push

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile'
      - 'apps/**'
      - 'requirements.txt'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build & push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ secrets.REGISTRY }}/${{ secrets.IMAGE_NAME_WEB }}:latest
            ${{ secrets.REGISTRY }}/${{ secrets.IMAGE_NAME_API }}:latest
          platforms: linux/amd64,linux/arm64
          file: ./Dockerfile
          context: .
